"""
drafter.py — Undermind's light inference engine (the subconscious's drafter).

generate_endpoints() now calls the LOCAL 1.5B (Ollama, :11434) to propose
candidate branch responses in parallel — the "subconscious proposes" half of
speculative decoding. undermind.py prunes those branches by live stream
overlap and selects the pre-ready one.

If Ollama is unreachable, it falls back to a keyword fan (_mock_fan) so the
daemon never crashes. No OS keys, no off-box traffic — pure localhost.
"""
from itertools import product

# Topic taxonomy: the drafter's candidate buckets. Real version pulls these
# from the associative memory store.
TOPICS = {
    "greeting": {"hi", "hello", "hey", "sup"},
    "coding": {"code", "build", "python", "bug", "function", "deploy", "test"},
    "hardware": {"pi", "npu", "gpu", "ram", "model", "server", "lmstudio"},
    "evolution": {"evolve", "undermind", "subconscious", "learn", "grow"},
    "osint": {"find", "locate", "person", "search", "missing", "where"},
    "ops": {"run", "start", "stop", "restart", "status", "logs", "config"},
}
INTENTS = ["acknowledge", "question", "propose", "challenge", "build", "summarize"]

def _topic_of(words):
    """Return the dominant topic for a set of stream words."""
    hits = {}
    for topic, kws in TOPICS.items():
        hits[topic] = len(kws & words)
    best = max(hits, key=hits.get)
    return best if hits[best] > 0 else "coding"

def generate_endpoints(seed_words, n=1000):
    """
    REAL drafter: fan out ~n candidate branches, with the pre-ready
    RESPONSE text generated by the local 1.5B (Ollama, :11434). The tiny
    model proposes in parallel; undermind.py prunes by live stream overlap.

    Returns the same branch shape as the mock so pruning/select are unchanged:
      {"id", "topic", "intent", "sig", "response", "score"}
    Topic/intent are sampled from the taxonomy so the existing prune logic
    still narrows the beam; the *response* is the real model's wording.
    Falls back to the mock fan if Ollama is unreachable (daemon never crashes).
    """
    words = [w.lower() for w in seed_words]
    try:
        import urllib.request, json
        branches = []
        # ask the drafter for a diverse set of candidate completions
        prompt = (
            "You are a fast subconscious drafter. Given the partial thought: "
            f"'{' '.join(words)}' -- generate {min(n, 20)} distinct, short, "
            "plausible ways this thought could continue or be responded to. "
            "One per line. No numbering."
        )
        req = urllib.request.Request(
            "http://localhost:11434/api/generate",
            data=json.dumps({
                "model": "qwen2.5:1.5b",
                "prompt": prompt,
                "stream": False,
                "temperature": 0.9,
                "top_p": 0.95,
            }).encode(),
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            out = json.load(resp)
        candidates = [c.strip(" -0123456789.") for c in out.get("response", "").splitlines() if c.strip()]
        if not candidates:
            raise RuntimeError("empty drafter output")
        # map each candidate onto a topic/intent for pruning compatibility
        for i, cand in enumerate(candidates):
            top = _topic_of(set(words))
            intent = INTENTS[i % len(INTENTS)]
            branches.append({
                "id": f"draft:{top}:{intent}:{i}",
                "topic": top,
                "intent": intent,
                "sig": TOPICS.get(top, set()),
                "response": cand,
                "score": 0.0,
            })
        return branches
    except Exception as e:
        # fallback: keep the daemon alive if the model is offline
        print(f"[drafter] Ollama unreachable ({e}); using mock fan")
        return _mock_fan(seed_words, n)

def assumed_context(words):
    """MOCK: the running 'where this is heading' trajectory string."""
    topic = _topic_of(set(w.lower() for w in words))
    return f"assumed-trajectory:{topic} <- {list(words)}"

def _mock_fan(seed_words, n=1000):
    """Fallback drafter: keyword fan when Ollama is offline (daemon stays alive)."""
    words = set(w.lower() for w in seed_words)
    branches = []
    combos = [(top, intent) for top in TOPICS for intent in INTENTS]
    per = max(1, n // len(combos))
    for (top, intent) in combos:
        kws = TOPICS[top]
        for i in range(per):
            sig = set(kws)
            resp = f"[{intent}] re: {top} ({i}) -- pre-ready branch response"
            branches.append({
                "id": f"mock:{top}:{intent}:{i}",
                "topic": top,
                "intent": intent,
                "sig": sig,
                "response": resp,
                "score": 0.0,
            })
            if len(branches) >= n:
                break
        if len(branches) >= n:
            break
    return branches
